import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useMemo, useState } from "react";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { formulary, searchDrugs } from "@/lib/formulary";
export default function DrugFormularyPage() {
    const [q, setQ] = useState("");
    const rows = useMemo(() => searchDrugs(q), [q]);
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { children: [_jsx("h1", { className: "text-2xl font-semibold", children: "Drug Formulary" }), _jsx("p", { className: "text-sm text-muted-foreground", children: "Hospital-approved medications list (demo data)." })] }), _jsxs(Card, { className: "rounded-2xl", children: [_jsx(CardHeader, { children: _jsx(CardTitle, { className: "text-base", children: "Search" }) }), _jsxs(CardContent, { className: "flex gap-3", children: [_jsx(Input, { value: q, onChange: (e) => setQ(e.target.value), placeholder: "Search by name / generic / strength / ATC..." }), _jsxs(Badge, { variant: "secondary", children: [rows.length, " drugs"] })] })] }), _jsxs(Card, { className: "rounded-2xl", children: [_jsx(CardHeader, { children: _jsx(CardTitle, { className: "text-base", children: "Formulary" }) }), _jsxs(CardContent, { children: [_jsx("div", { className: "rounded-xl border", children: _jsxs(Table, { children: [_jsx(TableHeader, { children: _jsxs(TableRow, { children: [_jsx(TableHead, { children: "Name" }), _jsx(TableHead, { children: "Strength" }), _jsx(TableHead, { children: "Form" }), _jsx(TableHead, { children: "Route" }), _jsx(TableHead, { children: "ATC" }), _jsx(TableHead, { children: "Tags" })] }) }), _jsxs(TableBody, { children: [rows.map((d) => (_jsxs(TableRow, { children: [_jsxs(TableCell, { className: "font-medium", children: [d.name, d.genericName && d.genericName !== d.name ? (_jsx("div", { className: "text-xs text-muted-foreground", children: d.genericName })) : null] }), _jsx(TableCell, { children: d.strength ?? "-" }), _jsx(TableCell, { children: d.form ?? "-" }), _jsx(TableCell, { children: d.route }), _jsx(TableCell, { className: "text-xs", children: d.atc ?? "-" }), _jsx(TableCell, { className: "space-x-1", children: (d.tags ?? []).slice(0, 3).map((t) => (_jsx(Badge, { variant: "secondary", children: t }, t))) })] }, d.id))), rows.length === 0 ? (_jsx(TableRow, { children: _jsx(TableCell, { colSpan: 6, className: "text-sm text-muted-foreground", children: "No matches." }) })) : null] })] }) }), _jsxs("div", { className: "mt-3 text-xs text-muted-foreground", children: ["Demo formulary (", formulary.length, " items). Later we connect to real drug database / national formulary."] })] })] })] }));
}
