server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;
    gzip on;
    resolver 8.8.8.8 1.1.1.1 valid=30s;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* ^/(auth|patients|doctors|appointments|notes|orders|alerts|labs|mar|drug-intel|radiology|specialties|reports|nursing|ai|pacs|patient|claude|fhir|audit|tenant|tenants) {
        set $backend "https://zesty-recreation-production-6b62.up.railway.app";
        proxy_pass $backend;
        proxy_set_header Host zesty-recreation-production-6b62.up.railway.app;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_http_version 1.1;
        proxy_read_timeout 60s;
        proxy_ssl_verify off;
        proxy_ssl_server_name on;
        proxy_ssl_name zesty-recreation-production-6b62.up.railway.app;
    }

    location /ws/ {
        resolver 8.8.8.8 1.1.1.1 valid=30s;
        set $ws_backend "https://zesty-recreation-production-6b62.up.railway.app";
        proxy_pass $ws_backend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 3600s;
        proxy_ssl_verify off;
        proxy_ssl_server_name on;
    }
}
