server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;
    gzip on;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* ^/(auth|patients|doctors|appointments|notes|orders|alerts|labs|mar|drug-intel|radiology|specialties|reports|nursing|ai|pacs|patient|claude|fhir|audit|tenant|tenants) {
        proxy_pass https://zesty-recreation-production-6b62.up.railway.app;
        proxy_set_header Host zesty-recreation-production-6b62.up.railway.app;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 60s;
    }

    location /ws/ {
        proxy_pass https://zesty-recreation-production-6b62.up.railway.app/ws/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 3600s;
    }
}
