from __future__ import annotations

from contextlib import nullcontext
from typing import Any

from sqlalchemy import inspect as sa_inspect
from sqlalchemy import text


class PostgresTenantExportRepository:
    """Read-only canonical tenant export data authority.

    Security / scope rules:
      * tenant scope is verified against principal -> hospital -> tenant;
      * table selection is an explicit whitelist;
      * AHOS28 / platform-internal tables are never readable here;
      * all SQL generated by this class is SELECT-only;
      * this repository does not create packages or write database state.
    """

    TABLE_STRATEGIES: dict[str, str] = {
        "ai_inference_runs": "VIA_PATIENT",
        "alerts": "VIA_PATIENT",
        "appointments": "VIA_PATIENT",
        "audit_logs": "DIRECT_TENANT_ONLY",
        "clinical_notes": "VIA_PATIENT",
        "clinical_orders": "VIA_PATIENT",
        "departments": "VIA_HOSPITAL",
        "doctor_assignments": "VIA_PATIENT",
        "doctors": "VIA_HOSPITAL",
        "hospitals": "DIRECT_TENANT",
        "lab_orders": "VIA_PATIENT",
        "mar_items": "VIA_PATIENT",
        "medication_orders_simple": "VIA_PATIENT",
        "nursing_notes": "VIA_PATIENT",
        "nursing_vitals": "VIA_PATIENT",
        "ophthalmology_ai_analyses": "DIRECT_TENANT",
        "ophthalmology_annotations": "DIRECT_TENANT",
        "ophthalmology_attendance_outcomes": "DIRECT_TENANT",
        "ophthalmology_audit_logs": "DIRECT_TENANT",
        "ophthalmology_cases": "DIRECT_TENANT",
        "ophthalmology_clinical_reviews": "DIRECT_TENANT",
        "ophthalmology_closed_loop_pathways": "DIRECT_TENANT",
        "ophthalmology_doctor_agreements": "DIRECT_TENANT",
        "ophthalmology_fp_fn_registry": "DIRECT_TENANT",
        "ophthalmology_patient_communications": "DIRECT_TENANT",
        "ophthalmology_pilot_enrollments": "DIRECT_TENANT",
        "ophthalmology_pilot_protocol_items": "DIRECT_TENANT",
        "ophthalmology_pilot_protocols": "DIRECT_TENANT",
        "ophthalmology_pilot_readiness": "DIRECT_TENANT",
        "ophthalmology_pilot_risk_register": "DIRECT_TENANT",
        "ophthalmology_reports": "DIRECT_TENANT",
        "ophthalmology_triage_queue": "DIRECT_TENANT",
        "ophthalmology_validation_evidence_reports": "DIRECT_TENANT",
        "patients": "VIA_HOSPITAL",
        "radiology_orders": "VIA_PATIENT",
        "refresh_tokens": "VIA_USER_TEXT_ID",
        "report_content_digests": "VIA_REPORT",
        "report_content_macs": "VIA_REPORT",
        "report_verification_events": "VIA_REPORT",
        "reports": "VIA_PATIENT",
        "tenants": "TENANT_ROOT",
        "users": "VIA_HOSPITAL",
    }

    FIELD_EXCLUSIONS: dict[str, frozenset[str]] = {
        "tenants": frozenset({"api_key"}),
        "users": frozenset({"password"}),
        "refresh_tokens": frozenset({"token_hash"}),
    }

    PLATFORM_INTERNAL_TABLES = frozenset({
        "alembic_version",
        "tenant_identity_bridge",
    })

    def __init__(self, engine: Any):
        self.engine = engine
        self._inspector = sa_inspect(engine)

    @staticmethod
    def _quote_identifier(value: str) -> str:
        return '"' + value.replace('"', '""') + '"'

    @classmethod
    def export_tables(cls) -> tuple[str, ...]:
        return tuple(sorted(cls.TABLE_STRATEGIES))

    @classmethod
    def excluded_fields_for_table(
        cls,
        table: str,
    ) -> frozenset[str]:
        return cls.FIELD_EXCLUSIONS.get(
            table,
            frozenset(),
        )

    def _select_projection(
        self,
        table: str,
        connection: Any | None = None,
    ) -> str:
        """Return an explicit SQL projection with secrets excluded.

        Sensitive fields are removed from the SELECT list itself so
        credential material is not fetched into application memory.
        """

        if table not in self.TABLE_STRATEGIES:
            raise ValueError(
                f"Tenant export table is not allowed: {table}"
            )

        excluded = self.excluded_fields_for_table(
            table
        )

        inspector = (
            sa_inspect(connection)
            if connection is not None
            else self._inspector
        )

        column_names = [
            item["name"]
            for item in inspector.get_columns(
                table,
                schema="public",
            )
            if item["name"] not in excluded
        ]

        if not column_names:
            raise RuntimeError(
                f"Tenant export projection is empty: {table}"
            )

        return ", ".join(
            "x."
            + self._quote_identifier(
                name
            )
            for name in column_names
        )

    def resolve_scope(
        self,
        *,
        tenant_id: str,
        principal_user_id: int,
        connection: Any | None = None,
    ) -> dict[str, Any]:

        tenant_id = str(
            tenant_id or ""
        ).strip()

        if not tenant_id:
            raise PermissionError(
                "Verified tenant scope is required"
            )

        try:
            principal_user_id = int(
                principal_user_id
            )
        except (TypeError, ValueError) as exc:
            raise PermissionError(
                "Verified principal is invalid"
            ) from exc

        connection_context = (
            nullcontext(connection)
            if connection is not None
            else self.engine.connect()
        )

        with connection_context as active_connection:
            row = (
                active_connection.execute(
                    text(
                        """
                        SELECT
                            u.id AS user_id,
                            u.hospital_id AS hospital_id,
                            h.tenant_id AS tenant_id
                        FROM public.users AS u
                        JOIN public.hospitals AS h
                          ON h.id = u.hospital_id
                        WHERE u.id = :principal_user_id
                        LIMIT 1
                        """
                    ),
                    {
                        "principal_user_id":
                        principal_user_id,
                    },
                )
                .mappings()
                .first()
            )

        if row is None:
            raise PermissionError(
                "Principal scope unavailable"
            )

        derived_tenant_id = str(
            row["tenant_id"] or ""
        ).strip()

        if (
            not derived_tenant_id
            or derived_tenant_id != tenant_id
        ):
            raise PermissionError(
                "Tenant scope denied"
            )

        return {
            "principal_user_id":
            principal_user_id,
            "tenant_id":
            derived_tenant_id,
            "hospital_id":
            str(row["hospital_id"]),
        }

    def hospital_ids_for_principal(
        self,
        *,
        tenant_id: str,
        principal_user_id: int,
        connection: Any | None = None,
    ) -> list[str]:

        scope = self.resolve_scope(
            tenant_id=tenant_id,
            principal_user_id=principal_user_id,
            connection=connection,
        )

        connection_context = (
            nullcontext(connection)
            if connection is not None
            else self.engine.connect()
        )

        with connection_context as active_connection:
            rows = (
                active_connection.execute(
                    text(
                        """
                        SELECT id
                        FROM public.hospitals
                        WHERE tenant_id = :tenant_id
                        ORDER BY id
                        """
                    ),
                    {
                        "tenant_id":
                        scope["tenant_id"],
                    },
                )
                .scalars()
                .all()
            )

        return [
            str(value)
            for value in rows
        ]

    def _select_sql(
        self,
        table: str,
        connection: Any | None = None,
    ) -> str:

        if table not in self.TABLE_STRATEGIES:
            raise ValueError(
                f"Tenant export table is not allowed: {table}"
            )

        strategy = self.TABLE_STRATEGIES[
            table
        ]

        qt = self._quote_identifier(
            table
        )

        projection = self._select_projection(
            table,
            connection=connection,
        )

        if strategy == "TENANT_ROOT":
            return (
                f"SELECT {projection} "
                f"FROM public.{qt} AS x "
                f"WHERE x.id = :tenant_id"
            )

        if strategy in {
            "DIRECT_TENANT",
            "DIRECT_TENANT_ONLY",
        }:
            return (
                f"SELECT {projection} "
                f"FROM public.{qt} AS x "
                f"WHERE x.tenant_id = :tenant_id"
            )

        if strategy == "VIA_HOSPITAL":
            return (
                f"SELECT {projection} "
                f"FROM public.{qt} AS x "
                f"JOIN public.hospitals AS h "
                f"ON h.id = x.hospital_id "
                f"WHERE h.tenant_id = :tenant_id"
            )

        if strategy == "VIA_PATIENT":
            return (
                f"SELECT {projection} "
                f"FROM public.{qt} AS x "
                f"JOIN public.patients AS p "
                f"ON p.id = x.patient_id "
                f"JOIN public.hospitals AS h "
                f"ON h.id = p.hospital_id "
                f"WHERE h.tenant_id = :tenant_id"
            )

        if strategy == "VIA_USER_TEXT_ID":
            return (
                f"SELECT {projection} "
                f"FROM public.{qt} AS x "
                f"JOIN public.users AS u "
                f"ON u.id::text = BTRIM(x.user_id) "
                f"JOIN public.hospitals AS h "
                f"ON h.id = u.hospital_id "
                f"WHERE h.tenant_id = :tenant_id"
            )

        if strategy == "VIA_REPORT":
            return (
                f"SELECT {projection} "
                f"FROM public.{qt} AS x "
                f"JOIN public.reports AS r "
                f"ON r.id = x.report_id "
                f"JOIN public.patients AS p "
                f"ON p.id = r.patient_id "
                f"JOIN public.hospitals AS h "
                f"ON h.id = p.hospital_id "
                f"WHERE h.tenant_id = :tenant_id"
            )

        raise RuntimeError(
            f"Unsupported export strategy: {strategy}"
        )

    def read_tenant_export_rows(
        self,
        *,
        table: str,
        tenant_id: str,
        principal_user_id: int,
        connection: Any | None = None,
    ) -> list[dict[str, Any]]:

        scope = self.resolve_scope(
            tenant_id=tenant_id,
            principal_user_id=principal_user_id,
            connection=connection,
        )

        sql = self._select_sql(
            table,
            connection=connection,
        )

        connection_context = (
            nullcontext(connection)
            if connection is not None
            else self.engine.connect()
        )

        with connection_context as active_connection:
            rows = (
                active_connection.execute(
                    text(sql),
                    {
                        "tenant_id":
                        scope["tenant_id"],
                    },
                )
                .mappings()
                .all()
            )

        return [
            dict(row)
            for row in rows
        ]

    def count_unscoped_exclusions(
        self,
    ) -> dict[str, int]:
        """Count current rows that cannot be attributed to a tenant.

        These counts are evidence for internal manifest construction only.
        They do not assign an unscoped row to any tenant.
        """

        with self.engine.connect() as connection:

            alerts = connection.execute(
                text(
                    """
                    SELECT COUNT(*)
                    FROM public.alerts AS a
                    LEFT JOIN public.patients AS p
                      ON p.id = a.patient_id
                    LEFT JOIN public.hospitals AS h
                      ON h.id = p.hospital_id
                    LEFT JOIN public.tenants AS t
                      ON t.id = h.tenant_id
                    WHERE t.id IS NULL
                    """
                )
            ).scalar_one()

            audit_logs = connection.execute(
                text(
                    """
                    SELECT COUNT(*)
                    FROM public.audit_logs AS a
                    LEFT JOIN public.tenants AS t
                      ON t.id = a.tenant_id
                    WHERE t.id IS NULL
                    """
                )
            ).scalar_one()

        return {
            "alerts": int(alerts),
            "audit_logs": int(audit_logs),
        }

    def excluded_tables(
        self,
        connection: Any | None = None,
    ) -> list[dict[str, str]]:

        inspector = (
            sa_inspect(connection)
            if connection is not None
            else self._inspector
        )

        public_tables = sorted(
            inspector.get_table_names(
                schema="public",
            )
        )

        allowed = set(
            self.TABLE_STRATEGIES
        )

        excluded: list[
            dict[str, str]
        ] = []

        for table in public_tables:

            if table in allowed:
                continue

            if table.startswith(
                "ahos_28_"
            ):
                reason = (
                    "LEGACY_AHOS28_UNBRIDGED"
                )

            elif table in (
                self.PLATFORM_INTERNAL_TABLES
            ):
                reason = (
                    "PLATFORM_INTERNAL"
                )

            else:
                reason = (
                    "UNCLASSIFIED_NOT_WHITELISTED"
                )

            excluded.append({
                "table": table,
                "reason": reason,
            })

        return excluded
