from __future__ import annotations

from contextlib import nullcontext
from typing import Any

from sqlalchemy import inspect as sa_inspect
from sqlalchemy import text


class PostgresTenantExportRepository:
    """Read-only canonical tenant export data authority.

    Security / scope rules:
      * tenant scope is verified against principal -> hospital -> tenant;
      * table selection is an explicit whitelist;
      * AHOS28 / platform-internal tables are never readable here;
      * all SQL generated by this class is SELECT-only;
      * this repository does not create packages or write database state.
    """

    TABLE_STRATEGIES: dict[str, str] = {
        "ai_inference_runs": "VIA_PATIENT",
        "alerts": "VIA_PATIENT",
        "appointments": "VIA_PATIENT",
        "audit_logs": "DIRECT_TENANT_ONLY",
        "clinical_notes": "VIA_PATIENT",
        "clinical_orders": "VIA_PATIENT",
        "departments": "VIA_HOSPITAL",
        "doctor_assignments": "VIA_PATIENT",
        "doctors": "VIA_HOSPITAL",
        "hospitals": "DIRECT_TENANT",
        "lab_orders": "VIA_PATIENT",
        "mar_items": "VIA_PATIENT",
        "medication_orders_simple": "VIA_PATIENT",
        "nursing_notes": "VIA_PATIENT",
        "nursing_vitals": "VIA_PATIENT",
        "ophthalmology_ai_analyses": "DIRECT_TENANT",
        "ophthalmology_annotations": "DIRECT_TENANT",
        "ophthalmology_attendance_outcomes": "DIRECT_TENANT",
        "ophthalmology_audit_logs": "DIRECT_TENANT",
        "ophthalmology_cases": "DIRECT_TENANT",
        "ophthalmology_clinical_reviews": "DIRECT_TENANT",
        "ophthalmology_closed_loop_pathways": "DIRECT_TENANT",
        "ophthalmology_doctor_agreements": "DIRECT_TENANT",
        "ophthalmology_fp_fn_registry": "DIRECT_TENANT",
        "ophthalmology_patient_communications": "DIRECT_TENANT",
        "ophthalmology_pilot_enrollments": "DIRECT_TENANT",
        "ophthalmology_pilot_protocol_items": "DIRECT_TENANT",
        "ophthalmology_pilot_protocols": "DIRECT_TENANT",
        "ophthalmology_pilot_readiness": "DIRECT_TENANT",
        "ophthalmology_pilot_risk_register": "DIRECT_TENANT",
        "ophthalmology_reports": "DIRECT_TENANT",
        "ophthalmology_triage_queue": "DIRECT_TENANT",
        "ophthalmology_validation_evidence_reports": "DIRECT_TENANT",
        "patients": "VIA_HOSPITAL",
        "radiology_orders": "VIA_PATIENT",
        "report_content_digests": "VIA_REPORT",
        "report_content_macs": "VIA_REPORT",
        "report_verification_events": "VIA_REPORT",
        "reports": "VIA_PATIENT",
        "tenants": "TENANT_ROOT",
        "users": "VIA_HOSPITAL",
    }

    PORTABILITY_EXCLUDED_TABLES: dict[str, str] = {
        "refresh_tokens": (
            "PLATFORM_AUTHENTICATION_SECURITY_STATE"
        ),
        "tenant_data_lifecycle": (
            "NON_PORTABLE_GOVERNANCE_STATE"
        ),
        "tenant_data_lifecycle_events": (
            "NON_PORTABLE_GOVERNANCE_AUDIT_STATE"
        ),
    }

    FIELD_EXCLUSIONS: dict[str, frozenset[str]] = {
        "tenants": frozenset({"api_key"}),
        "users": frozenset({"password"}),
    }

    EXPORT_FIELD_ALLOWLIST: dict[str, tuple[str, ...]] = {
        "ai_inference_runs": (
            "id",
            "patient_id",
            "model_type",
            "input_path",
            "result",
            "risk_level",
            "requested_by",
            "created_at",
        ),
        "alerts": (
            "id",
            "patient_id",
            "message",
            "severity",
            "source",
            "is_read",
            "created_at",
        ),
        "appointments": (
            "id",
            "patient_id",
            "doctor_id",
            "department",
            "date",
            "time",
            "status",
            "created_at",
        ),
        "audit_logs": (
            "id",
            "user_id",
            "action",
            "resource",
            "resource_id",
            "details",
            "ip_address",
            "success",
            "timestamp",
            "tenant_id",
        ),
        "clinical_notes": (
            "id",
            "patient_id",
            "author_id",
            "text",
            "created_at",
        ),
        "clinical_orders": (
            "id",
            "patient_id",
            "author_id",
            "item",
            "type",
            "priority",
            "status",
            "created_at",
            "updated_at",
        ),
        "departments": (
            "id",
            "name",
            "code",
            "hospital_id",
        ),
        "doctor_assignments": (
            "id",
            "doctor_id",
            "patient_id",
            "condition",
            "status",
            "assigned_at",
        ),
        "doctors": (
            "id",
            "name",
            "specialty",
            "department_id",
            "hospital_id",
            "experience",
            "status",
            "rating",
            "patients_count",
            "schedule",
            "phone",
            "created_at",
        ),
        "hospitals": (
            "id",
            "name",
            "address",
            "phone",
            "created_at",
            "tenant_id",
        ),
        "lab_orders": (
            "id",
            "patient_id",
            "ordered_by",
            "section",
            "tests",
            "priority",
            "status",
            "result",
            "created_at",
            "updated_at",
        ),
        "mar_items": (
            "id",
            "patient_id",
            "medication",
            "dose",
            "route",
            "schedule",
            "status",
            "given_at",
            "pharmacy_review",
            "ai_flag",
            "created_at",
            "updated_at",
        ),
        "medication_orders_simple": (
            "id",
            "patient_id",
            "drug_name",
            "generic_name",
            "dose",
            "route",
            "frequency",
            "duration_days",
            "quantity",
            "is_active",
            "created_at",
        ),
        "nursing_notes": (
            "id",
            "patient_id",
            "nurse_id",
            "text",
            "created_at",
        ),
        "nursing_vitals": (
            "id",
            "patient_id",
            "nurse_id",
            "temperature",
            "blood_pressure",
            "heart_rate",
            "respiratory_rate",
            "oxygen_saturation",
            "recorded_at",
            "display_time",
        ),
        "ophthalmology_ai_analyses": (
            "tenant_id",
            "hospital_id",
            "analysis_id",
            "case_id",
            "patient_id",
            "image_type",
            "filename",
            "width",
            "height",
            "mode",
            "quality_score",
            "brightness",
            "contrast",
            "sharpness",
            "risk_score",
            "risk_level",
            "findings_json",
            "recommendations_json",
            "safety_gate",
            "clinical_status",
            "created_at",
        ),
        "ophthalmology_annotations": (
            "tenant_id",
            "hospital_id",
            "annotation_id",
            "analysis_id",
            "case_id",
            "patient_id",
            "annotation_type",
            "shape",
            "x_percent",
            "y_percent",
            "width_percent",
            "height_percent",
            "marker_x_percent",
            "marker_y_percent",
            "severity",
            "doctor_note",
            "doctor_name",
            "status",
            "created_at",
            "updated_at",
        ),
        "ophthalmology_attendance_outcomes": (
            "tenant_id",
            "hospital_id",
            "attendance_id",
            "communication_id",
            "triage_id",
            "case_id",
            "analysis_id",
            "patient_id",
            "patient_confirmation",
            "attendance_status",
            "appointment_status",
            "outcome_type",
            "absence_reason",
            "reschedule_date",
            "reschedule_required",
            "doctor_note",
            "admin_note",
            "updated_by",
            "created_at",
            "updated_at",
        ),
        "ophthalmology_audit_logs": (
            "tenant_id",
            "hospital_id",
            "audit_id",
            "case_id",
            "action",
            "details",
            "created_at",
        ),
        "ophthalmology_cases": (
            "tenant_id",
            "hospital_id",
            "case_id",
            "patient_id",
            "filename",
            "stored_path",
            "image_type",
            "language",
            "risk_score",
            "risk_level",
            "status",
            "ai_summary",
            "clinical_notice",
            "doctor_review_status",
            "doctor_review_decision",
            "created_at",
            "updated_at",
        ),
        "ophthalmology_clinical_reviews": (
            "tenant_id",
            "hospital_id",
            "review_id",
            "analysis_id",
            "case_id",
            "patient_id",
            "decision",
            "priority",
            "review_status",
            "doctor_name",
            "doctor_signature",
            "review_note",
            "follow_up_plan",
            "annotation_count",
            "ai_risk_score",
            "ai_risk_level",
            "safety_gate",
            "created_at",
            "updated_at",
        ),
        "ophthalmology_closed_loop_pathways": (
            "tenant_id",
            "hospital_id",
            "pathway_id",
            "case_id",
            "analysis_id",
            "patient_id",
            "completion_score",
            "pathway_status",
            "final_operational_status",
            "case_created",
            "ai_analysis_done",
            "viewer_ready",
            "annotation_done",
            "review_done",
            "dossier_done",
            "triage_done",
            "communication_done",
            "attendance_done",
            "final_summary",
            "clinical_status",
            "created_at",
            "updated_at",
        ),
        "ophthalmology_doctor_agreements": (
            "tenant_id",
            "hospital_id",
            "agreement_id",
            "enrollment_id",
            "protocol_id",
            "case_id",
            "analysis_id",
            "patient_id",
            "ai_risk_score",
            "ai_risk_level",
            "ai_finding",
            "doctor_decision",
            "doctor_diagnosis",
            "agreement_status",
            "disagreement_reason",
            "safety_override",
            "follow_up_required",
            "validation_status",
            "doctor_name",
            "doctor_note",
            "created_at",
            "updated_at",
        ),
        "ophthalmology_fp_fn_registry": (
            "tenant_id",
            "hospital_id",
            "registry_id",
            "agreement_id",
            "enrollment_id",
            "case_id",
            "analysis_id",
            "patient_id",
            "ai_risk_score",
            "ai_risk_level",
            "doctor_decision",
            "agreement_status",
            "evidence_type",
            "evidence_reason",
            "safety_impact",
            "created_at",
        ),
        "ophthalmology_patient_communications": (
            "tenant_id",
            "hospital_id",
            "communication_id",
            "triage_id",
            "case_id",
            "analysis_id",
            "patient_id",
            "patient_contact",
            "channel",
            "message_type",
            "message_language",
            "message_subject",
            "message_body",
            "communication_status",
            "patient_confirmation",
            "confirmation_note",
            "scheduled_send_at",
            "sent_at",
            "created_by",
            "created_at",
            "updated_at",
        ),
        "ophthalmology_pilot_enrollments": (
            "tenant_id",
            "hospital_id",
            "enrollment_id",
            "protocol_id",
            "readiness_id",
            "case_id",
            "analysis_id",
            "patient_id",
            "enrollment_status",
            "consent_status",
            "image_quality_status",
            "doctor_review_status",
            "validation_status",
            "enrollment_note",
            "created_by",
            "created_at",
            "updated_at",
        ),
        "ophthalmology_pilot_protocol_items": (
            "tenant_id",
            "hospital_id",
            "item_id",
            "protocol_id",
            "section",
            "item_title",
            "item_description",
            "item_status",
            "item_score",
            "owner",
            "created_at",
            "updated_at",
        ),
        "ophthalmology_pilot_protocols": (
            "tenant_id",
            "hospital_id",
            "protocol_id",
            "readiness_id",
            "pathway_id",
            "case_id",
            "patient_id",
            "study_title",
            "pilot_site",
            "principal_investigator",
            "study_objective",
            "study_duration",
            "target_cases",
            "pilot_departments",
            "device_source",
            "protocol_status",
            "execution_status",
            "ethics_status",
            "governance_status",
            "clinical_production_status",
            "go_no_go_decision",
            "pilot_protocol_score",
            "final_summary",
            "created_at",
            "updated_at",
        ),
        "ophthalmology_pilot_readiness": (
            "tenant_id",
            "hospital_id",
            "readiness_id",
            "pathway_id",
            "case_id",
            "analysis_id",
            "patient_id",
            "technical_readiness",
            "pilot_readiness_score",
            "clinical_safety_score",
            "doctor_validation_score",
            "data_governance_score",
            "cybersecurity_score",
            "regulatory_score",
            "operational_score",
            "communication_score",
            "closed_loop_score",
            "go_no_go_decision",
            "governance_status",
            "regulatory_status",
            "clinical_production_status",
            "final_summary",
            "created_at",
            "updated_at",
        ),
        "ophthalmology_pilot_risk_register": (
            "tenant_id",
            "hospital_id",
            "risk_id",
            "readiness_id",
            "risk_category",
            "risk_title",
            "risk_level",
            "risk_description",
            "mitigation_plan",
            "owner",
            "status",
            "created_at",
            "updated_at",
        ),
        "ophthalmology_reports": (
            "tenant_id",
            "hospital_id",
            "report_id",
            "case_id",
            "patient_id",
            "report_type",
            "risk_score",
            "risk_level",
            "language",
            "created_at",
        ),
        "ophthalmology_triage_queue": (
            "tenant_id",
            "hospital_id",
            "triage_id",
            "case_id",
            "analysis_id",
            "patient_id",
            "triage_priority",
            "triage_status",
            "assigned_doctor",
            "department_unit",
            "appointment_date",
            "appointment_status",
            "patient_contact",
            "triage_reason",
            "follow_up_notes",
            "latest_decision",
            "latest_risk_score",
            "latest_risk_level",
            "safety_gate",
            "created_at",
            "updated_at",
        ),
        "ophthalmology_validation_evidence_reports": (
            "tenant_id",
            "hospital_id",
            "evidence_id",
            "protocol_id",
            "enrollment_count",
            "agreement_count",
            "agreement_rate",
            "disagreement_rate",
            "partial_agreement_rate",
            "review_completion_rate",
            "sensitivity_placeholder",
            "specificity_placeholder",
            "true_positive_count",
            "true_negative_count",
            "false_positive_count",
            "false_negative_count",
            "safety_override_count",
            "follow_up_required_count",
            "validation_evidence_score",
            "evidence_status",
            "regulatory_evidence_status",
            "clinical_production_status",
            "final_summary",
            "created_at",
            "updated_at",
        ),
        "patients": (
            "id",
            "name",
            "age",
            "gender",
            "phone",
            "condition",
            "department_id",
            "hospital_id",
            "status",
            "admitted_at",
            "discharged_at",
            "created_at",
            "updated_at",
            "allergies",
            "blood_type",
            "chronic_conditions",
            "current_medications",
            "date_of_birth",
            "full_name",
            "insurance_provider",
            "mrn",
        ),
        "radiology_orders": (
            "id",
            "patient_id",
            "ordered_by",
            "section",
            "studies",
            "priority",
            "status",
            "study_uid",
            "report",
            "ai_result",
            "created_at",
            "updated_at",
        ),
        "report_content_digests": (
            "id",
            "report_id",
            "canonicalization_version",
            "digest_algorithm",
            "digest_hex",
            "secured_by_user_id",
            "secured_at",
        ),
        "report_content_macs": (
            "id",
            "report_id",
            "mac_version",
            "mac_algorithm",
            "mac_hex",
            "created_by_user_id",
            "created_at",
            "key_id",
        ),
        "report_verification_events": (
            "id",
            "report_id",
            "verification_type",
            "status",
            "verified_by_user_id",
            "verified_at",
        ),
        "reports": (
            "id",
            "patient_id",
            "author_id",
            "title",
            "type",
            "status",
            "body",
            "created_at",
            "updated_at",
            "summary",
        ),
        "tenants": (
            "id",
            "name",
            "slug",
            "plan",
            "admin_email",
            "admin_name",
            "country",
            "phone",
            "is_active",
            "is_verified",
            "trial_ends_at",
            "plan_starts_at",
            "plan_ends_at",
            "settings",
            "ai_calls_today",
            "ai_calls_reset_at",
            "created_at",
            "updated_at",
        ),
        "users": (
            "id",
            "username",
            "name",
            "role",
            "hospital_id",
            "is_active",
            "created_at",
            "last_login",
        ),
    }

    PLATFORM_INTERNAL_TABLES = frozenset({
        "alembic_version",
        "tenant_identity_bridge",
    })

    def __init__(self, engine: Any):
        self.engine = engine
        self._inspector = sa_inspect(engine)

    @staticmethod
    def _quote_identifier(value: str) -> str:
        return '"' + value.replace('"', '""') + '"'

    @classmethod
    def export_tables(cls) -> tuple[str, ...]:
        return tuple(sorted(cls.TABLE_STRATEGIES))

    @classmethod
    def excluded_fields_for_table(
        cls,
        table: str,
    ) -> frozenset[str]:
        return cls.FIELD_EXCLUSIONS.get(
            table,
            frozenset(),
        )

    def _select_projection(
        self,
        table: str,
        connection: Any | None = None,
    ) -> str:
        """Return the statically approved export projection.

        Exportability is fail-closed at the column level:
        runtime schema reflection does not authorize newly added
        database columns for tenant export.

        ``connection`` is retained for repository API compatibility
        but is intentionally not used for projection authorization.
        """

        if table not in self.TABLE_STRATEGIES:
            raise ValueError(
                f"Tenant export table is not allowed: {table}"
            )

        approved = self.EXPORT_FIELD_ALLOWLIST.get(
            table
        )

        if not approved:
            raise RuntimeError(
                "Tenant export field allowlist is missing "
                f"or empty: {table}"
            )

        excluded = self.excluded_fields_for_table(
            table
        )

        forbidden = sorted(
            set(approved) & set(excluded)
        )

        if forbidden:
            raise RuntimeError(
                "Tenant export allowlist contains "
                "defense-in-depth excluded fields for "
                f"{table}: {', '.join(forbidden)}"
            )

        return ", ".join(
            "x."
            + self._quote_identifier(name)
            for name in approved
        )

    def resolve_scope(
        self,
        *,
        tenant_id: str,
        principal_user_id: int,
        connection: Any | None = None,
    ) -> dict[str, Any]:

        tenant_id = str(
            tenant_id or ""
        ).strip()

        if not tenant_id:
            raise PermissionError(
                "Verified tenant scope is required"
            )

        try:
            principal_user_id = int(
                principal_user_id
            )
        except (TypeError, ValueError) as exc:
            raise PermissionError(
                "Verified principal is invalid"
            ) from exc

        connection_context = (
            nullcontext(connection)
            if connection is not None
            else self.engine.connect()
        )

        with connection_context as active_connection:
            row = (
                active_connection.execute(
                    text(
                        """
                        SELECT
                            u.id AS user_id,
                            u.hospital_id AS hospital_id,
                            h.tenant_id AS tenant_id
                        FROM public.users AS u
                        JOIN public.hospitals AS h
                          ON h.id = u.hospital_id
                        WHERE u.id = :principal_user_id
                        LIMIT 1
                        """
                    ),
                    {
                        "principal_user_id":
                        principal_user_id,
                    },
                )
                .mappings()
                .first()
            )

        if row is None:
            raise PermissionError(
                "Principal scope unavailable"
            )

        derived_tenant_id = str(
            row["tenant_id"] or ""
        ).strip()

        if (
            not derived_tenant_id
            or derived_tenant_id != tenant_id
        ):
            raise PermissionError(
                "Tenant scope denied"
            )

        return {
            "principal_user_id":
            principal_user_id,
            "tenant_id":
            derived_tenant_id,
            "hospital_id":
            str(row["hospital_id"]),
        }

    def hospital_ids_for_principal(
        self,
        *,
        tenant_id: str,
        principal_user_id: int,
        connection: Any | None = None,
    ) -> list[str]:

        scope = self.resolve_scope(
            tenant_id=tenant_id,
            principal_user_id=principal_user_id,
            connection=connection,
        )

        connection_context = (
            nullcontext(connection)
            if connection is not None
            else self.engine.connect()
        )

        with connection_context as active_connection:
            rows = (
                active_connection.execute(
                    text(
                        """
                        SELECT id
                        FROM public.hospitals
                        WHERE tenant_id = :tenant_id
                        ORDER BY id
                        """
                    ),
                    {
                        "tenant_id":
                        scope["tenant_id"],
                    },
                )
                .scalars()
                .all()
            )

        return [
            str(value)
            for value in rows
        ]

    def _select_sql(
        self,
        table: str,
        connection: Any | None = None,
    ) -> str:

        if table not in self.TABLE_STRATEGIES:
            raise ValueError(
                f"Tenant export table is not allowed: {table}"
            )

        strategy = self.TABLE_STRATEGIES[
            table
        ]

        qt = self._quote_identifier(
            table
        )

        projection = self._select_projection(
            table,
            connection=connection,
        )

        if strategy == "TENANT_ROOT":
            return (
                f"SELECT {projection} "
                f"FROM public.{qt} AS x "
                f"WHERE x.id = :tenant_id"
            )

        if strategy in {
            "DIRECT_TENANT",
            "DIRECT_TENANT_ONLY",
        }:
            return (
                f"SELECT {projection} "
                f"FROM public.{qt} AS x "
                f"WHERE x.tenant_id = :tenant_id"
            )

        if strategy == "VIA_HOSPITAL":
            return (
                f"SELECT {projection} "
                f"FROM public.{qt} AS x "
                f"JOIN public.hospitals AS h "
                f"ON h.id = x.hospital_id "
                f"WHERE h.tenant_id = :tenant_id"
            )

        if strategy == "VIA_PATIENT":
            return (
                f"SELECT {projection} "
                f"FROM public.{qt} AS x "
                f"JOIN public.patients AS p "
                f"ON p.id = x.patient_id "
                f"JOIN public.hospitals AS h "
                f"ON h.id = p.hospital_id "
                f"WHERE h.tenant_id = :tenant_id"
            )

        if strategy == "VIA_USER_TEXT_ID":
            return (
                f"SELECT {projection} "
                f"FROM public.{qt} AS x "
                f"JOIN public.users AS u "
                f"ON u.id::text = BTRIM(x.user_id) "
                f"JOIN public.hospitals AS h "
                f"ON h.id = u.hospital_id "
                f"WHERE h.tenant_id = :tenant_id"
            )

        if strategy == "VIA_REPORT":
            return (
                f"SELECT {projection} "
                f"FROM public.{qt} AS x "
                f"JOIN public.reports AS r "
                f"ON r.id = x.report_id "
                f"JOIN public.patients AS p "
                f"ON p.id = r.patient_id "
                f"JOIN public.hospitals AS h "
                f"ON h.id = p.hospital_id "
                f"WHERE h.tenant_id = :tenant_id"
            )

        raise RuntimeError(
            f"Unsupported export strategy: {strategy}"
        )

    def read_tenant_export_rows(
        self,
        *,
        table: str,
        tenant_id: str,
        principal_user_id: int,
        connection: Any | None = None,
    ) -> list[dict[str, Any]]:

        scope = self.resolve_scope(
            tenant_id=tenant_id,
            principal_user_id=principal_user_id,
            connection=connection,
        )

        sql = self._select_sql(
            table,
            connection=connection,
        )

        connection_context = (
            nullcontext(connection)
            if connection is not None
            else self.engine.connect()
        )

        with connection_context as active_connection:
            rows = (
                active_connection.execute(
                    text(sql),
                    {
                        "tenant_id":
                        scope["tenant_id"],
                    },
                )
                .mappings()
                .all()
            )

        return [
            dict(row)
            for row in rows
        ]

    def count_unscoped_exclusions(
        self,
    ) -> dict[str, int]:
        """Count current rows that cannot be attributed to a tenant.

        These counts are evidence for internal manifest construction only.
        They do not assign an unscoped row to any tenant.
        """

        with self.engine.connect() as connection:

            alerts = connection.execute(
                text(
                    """
                    SELECT COUNT(*)
                    FROM public.alerts AS a
                    LEFT JOIN public.patients AS p
                      ON p.id = a.patient_id
                    LEFT JOIN public.hospitals AS h
                      ON h.id = p.hospital_id
                    LEFT JOIN public.tenants AS t
                      ON t.id = h.tenant_id
                    WHERE t.id IS NULL
                    """
                )
            ).scalar_one()

            audit_logs = connection.execute(
                text(
                    """
                    SELECT COUNT(*)
                    FROM public.audit_logs AS a
                    LEFT JOIN public.tenants AS t
                      ON t.id = a.tenant_id
                    WHERE t.id IS NULL
                    """
                )
            ).scalar_one()

        return {
            "alerts": int(alerts),
            "audit_logs": int(audit_logs),
        }

    def excluded_tables(
        self,
        connection: Any | None = None,
    ) -> list[dict[str, str]]:

        inspector = (
            sa_inspect(connection)
            if connection is not None
            else self._inspector
        )

        public_tables = sorted(
            inspector.get_table_names(
                schema="public",
            )
        )

        allowed = set(
            self.TABLE_STRATEGIES
        )

        excluded: list[
            dict[str, str]
        ] = []

        for table in public_tables:

            if table in allowed:
                continue

            if table in (
                self.PORTABILITY_EXCLUDED_TABLES
            ):

                reason = (
                    self.PORTABILITY_EXCLUDED_TABLES[
                        table
                    ]
                )

            elif table.startswith(
                "ahos_28_"
            ):
                reason = (
                    "LEGACY_AHOS28_UNBRIDGED"
                )

            elif table in (
                self.PLATFORM_INTERNAL_TABLES
            ):
                reason = (
                    "PLATFORM_INTERNAL"
                )

            else:
                reason = (
                    "UNCLASSIFIED_NOT_WHITELISTED"
                )

            excluded.append({
                "table": table,
                "reason": reason,
            })

        return excluded
